### ISSUE TITLE
Script broken on e-hentai/exhentai

### ISSUE THREAD

**Issue by Twilicious** [hanFengSan/eHunter#198]
Ehentai changed some stuff for thumbnail and image loading and broke basically all my scripts. 
Here's the changelog: https://forums.e-hentai.org/index.php?showtopic=244935
Here's a sample of the code that was supposedly changed. https://forums.e-hentai.org/index.php?s=&showtopic=199743&view=findpost&p=6559928

Hopefully it's an easy fix, I would greatly miss using this very irreplaceable script.

Thanks for the hard work!

**Comment by gn01036238** [comment]
Can confirm, it is broken, on exhentai.
在exhentai上確實壞了

**Comment by loserwa** [comment]
为了特意前来这里说一声，该软件无法在exhentai上面使用，坏了，而特意注册了这个网站的账户。
![QQ截图20241025193203](https://github.com/user-attachments/assets/e86f9331-f39e-49c8-8cba-8367b9eec863)

**Comment by whs1353** [comment]
同上，大概一周前就用不了了

**Comment by loserwa** [comment]
周日回复或未必回复

**Comment by weidud** [comment]
希望能有更新😀

**Comment by FarrasR** [comment]
@hZeper can you make the update to the userscript too? https://openuserjs.org/scripts/alexchen/eHunter

**Comment by 108812976l** [comment]
> > Ehentai changed some stuff for thumbnail and image loading and broke basically all my scripts. Here's the changelog: https://forums.e-hentai.org/index.php?showtopic=244935 Here's a sample of the code that was supposedly changed. https://forums.e-hentai.org/index.php?s=&showtopic=199743&view=findpost&p=6559928
> > Hopefully it's an easy fix, I would greatly miss using this very irreplaceable script.
> > Thanks for the hard work!
> 
> yup it was an easy fix made a pull request at : #201 you can download an edited version of the script at : https://github.com/hZeper/eHunter/releases/tag/2.7.3-fixEXH-25102024
> 
> sadly I think this script is abandoned, it has many pull request waiting... maybe someone should to a true fork of it

how to use it,i mean  iam novice and i dont know how to use this zip

**Comment by 108812976l** [comment]
> > 如何使用它，我是说我是新手，我不知道如何使用这个 zip
> 
> 不要碰 .zip 下载inject.js 打开它 选择并复制所有内容 打开当前版本的eHunter然后粘贴以替换它

thanks 
It works correctly, although the image keeps loading
but I believe you will have a great update

**Comment by mbahArip** [comment]
> > Ehentai changed some stuff for thumbnail and image loading and broke basically all my scripts. Here's the changelog: https://forums.e-hentai.org/index.php?showtopic=244935 Here's a sample of the code that was supposedly changed. https://forums.e-hentai.org/index.php?s=&showtopic=199743&view=findpost&p=6559928
> > Hopefully it's an easy fix, I would greatly miss using this very irreplaceable script.
> > Thanks for the hard work!
> 
> yup it was an easy fix made a pull request at : #201 you can download an edited version of the script at : https://github.com/hZeper/eHunter/releases/tag/2.7.3-fixEXH-25102024
> 
> sadly I think this script is abandoned, it has many pull request waiting... maybe someone should to a true fork of it

Trying to use this fork but still stuck on read loading

decided to tinker a bit on the `getImgUrls` function to make it work on my device
but in case anyone having the same problem, you can try this by editing the `inject.js` and find `t.prototype.getImgUrls`
```ts
getImgUrls(): Array<ImgPageInfo> {
    if (this._isValidIntroPage()) {
        return Array.prototype
        .slice
        .call(this.html.querySelector("#gdt")?.children, 0)
        .map(item => {
            item.querySelector('div[style]').getAttribute('style').match(/width:(.*?)px;height:(.*?)px;/g);
            const thumbHeight = Number(RegExp.$2);
            const thumbWidth = Number(RegExp.$1);
            let pageUrl = item.children.getAttribute('href').match(/\/s.*$/) + '';
            return {
                id: pageUrl,
                index: 0,
                pageUrl,
                src: '',
                thumbHeight,
                thumbWidth,
                heightOfWidth: thumbHeight / thumbWidth
            }
        })
    } else {
        return [];
    }
}
```

Things I changed:
- I use ID selector `#gdt` instead of the class name to make sure it's still working whether you use 100x / 200x (normal / large in old version)
- `div[style]` to make sure it selected the div children that has style attribute

**Comment by xmcp** [comment]
https://github.com/xmcp/eHunter/tree/fix-198 is my fixed branch. The thumbnail issue is also fixed in this branch.

You can try the code here: [inject.zip](https://github.com/user-attachments/files/17526238/inject.zip)

**Comment by Secretsquirrel73** [comment]
So how do you use the inject or the 198 fix? I apologize for not knowing much. I barely know how to github itself.

**Comment by MacMJ3** [comment]
> [https://github.com/xmcp/eHunter/tree/fix-198 ](https://github.com/xmcp/eHunter/tree/fix-198) is my fixed branch. The thumbnail issue is also fixed in this branch (earlier in the fix-192 branch).
> 
> You can try the code here: [inject.zip ](https://github.com/user-attachments/files/17526345/inject.zip)

So how do you use the inject or the 198 fix? I apologize for not knowing much. I barely know how to github itself.

**Comment by Twilicious** [comment]
> So how do you use the inject or the 198 fix? I apologize for not knowing much. I barely know how to github itself.

> How can I use this fix? Any time I try to import the js file it reads as an invalid userscript.


Open the ehunter script in Violentmonkey and delete everything under the
// @license      MIT
// ==/UserScript==
lines. 

Then copy everything from the inject.js file in the zip and paste it there instead.
That's all I had to do to get it working for me.

**Comment by Secretsquirrel73** [comment]
> > So how do you use the inject or the 198 fix? I apologize for not knowing much. I barely know how to github itself.
> 
> > How can I use this fix? Any time I try to import the js file it reads as an invalid userscript.
> 
> Open the ehunter script in Violentmonkey and delete everything under the // @license MIT // ==/UserScript== lines.
> 
> Then copy everything from the inject.js file in the zip and paste it there instead. That's all I had to do to get it working for me.

Ok cool, how do you open a JS file. It only lets me open and then just errors out. Is there a program i need. Im willing to learn lol.

**Comment by AzureZakura** [comment]
> > So how do you use the inject or the 198 fix? I apologize for not knowing much. I barely know how to github itself.
> 
> > How can I use this fix? Any time I try to import the js file it reads as an invalid userscript.
> 
> Open the ehunter script in Violentmonkey and delete everything under the // @license WITH // ==/UserScript== lines.
> 
> Then copy everything from the inject.js file in the zip and paste it there instead. That's all I had to do to get it working for me.

When I try doing that the reader keeps loads endlessly. I'm not sure what's wrong.

**Comment by Twilicious** [comment]
> Ok cool, how do you open a JS file. It only lets me open and then just errors out. Is there a program i need. Im willing to learn lol.

I used Notepad++, it's free and open source.

> When I try doing that the reader keeps loads endlessly. I'm not sure what's wrong.

Not sure sorry, that's all I had to do. I'm using Violentmonkey and firefiox if that makes any difference. At this point someone with the know how just needs to make a proper fork and post the full working script on sleazyfork or something.
I added a screenshot of what my script window looks like if it helps. Good luck.
![Screenshot 2024-10-25 205830](https://github.com/user-attachments/assets/bd9c03d7-59ba-41ce-86b7-82c5fa0bb480)

**Comment by Secretsquirrel73** [comment]
> > Ok cool, how do you open a JS file. It only lets me open and then just errors out. Is there a program i need. Im willing to learn lol.
> 
> I used Notepad++, it's free and open source.
> 
> > When I try doing that the reader keeps loads endlessly. I'm not sure what's wrong.
> 
> Not sure sorry, that's all I had to do. I'm using Violentmonkey and firefiox if that makes any difference. At this point someone with the know how just needs to make a proper fork and post the full working script on sleazyfork or something. I added a screenshot of what my script window looks like if it helps. Good luck. ![Screenshot 2024-10-25 205830](https://private-user-images.githubusercontent.com/7462989/380361670-bd9c03d7-59ba-41ce-86b7-82c5fa0bb480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTU5ODYsIm5iZiI6MTcyOTkxNTY4NiwicGF0aCI6Ii83NDYyOTg5LzM4MDM2MTY3MC1iZDljMDNkNy01OWJhLTQxY2UtODZiNy04MmM1ZmEwYmI0ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMDQwODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjhiMWQ1NTY2ZTMzMjg0NWY2NjAwNmE5MWUxMjIyZDgyYWRiN2RiNTU2Y2U0MTEzMDMwMWJkNDlmYTg0MWZkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AVWvfVPzEKxrouvXno02Ad-Fm4s8xWM6D-o5JO-j_8o)

Yea I think its how we are posting it in there compared to yours. I know im doing Control A and selecting the entire notepad and pasting it in. I havent utilized anything from the zip file of the ehunter itself though. Tried it on firefox as well and still infinite reading bug.

**Comment by AzureZakura** [comment]
> > Ok cool, how do you open a JS file. It only lets me open and then just errors out. Is there a program i need. Im willing to learn lol.
> 
> I used Notepad++, it's free and open source.
> 
> > When I try doing that the reader keeps loads endlessly. I'm not sure what's wrong.
> 
> Not sure sorry, that's all I had to do. I'm using Violentmonkey and firefiox if that makes any difference. At this point someone with the know how just needs to make a proper fork and post the full working script on sleazyfork or something. I added a screenshot of what my script window looks like if it helps. Good luck. ![Screenshot 2024-10-25 205830](https://private-user-images.githubusercontent.com/7462989/380361670-bd9c03d7-59ba-41ce-86b7-82c5fa0bb480.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MTU0OTIsIm5iZiI6MTcyOTkxNTE5MiwicGF0aCI6Ii83NDYyOTg5LzM4MDM2MTY3MC1iZDljMDNkNy01OWJhLTQxY2UtODZiNy04MmM1ZmEwYmI0ODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjZUMDM1OTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWI4MGNlZTI1MGNjMGI3OTFkODMzN2Y2ZGJiMjRmZDZiMzBhOGM0MjIyYTYwMjIxM2I0YmQ4OWNhOGU1NWFiZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Y_yIsCQ4KxoZ5nCmn7b0iUL9keVwL61-O_l2sg9NVmE)

I also use notepad++, and copied but still get the infinite reading bug. Used Firefox and tried on both tampermonkey and violentmonkey.

**Comment by Secretsquirrel73** [comment]
Possible we didnt put that 198 folder contents somewhere? I know i downloaded it but i didnt do anything with it.

**Comment by DOOMxKID** [comment]
> https://github.com/xmcp/eHunter/tree/fix-198 is my fixed branch. The thumbnail issue is also fixed in this branch (earlier in the fix-192 branch).
> 
> You can try the code here: [inject.zip](https://github.com/user-attachments/files/17526345/inject.zip)

Sorry, bug my eHunter keep loading the reading endless after use this fix code. I just copy all code inject.js to eHunter and overwrite  code below 【// ==/UserScript==】, did I do something wrong?

**Comment by Twilicious** [comment]
> I also use notepad++, and copied but still get the infinite reading bug. Used Firefox and tried on both tampermonkey and violentmonkey. Is it possible for you to save and post the edited version of your ehunter to test for myself?

Here you go, copied right from my violentmonkey script editor into notepad++.
Sorry i cant be of more help.
[ehunter.zip](https://github.com/user-attachments/files/17529036/ehunter.zip)

**Comment by DOOMxKID** [comment]
> > I also use notepad++, and copied but still get the infinite reading bug. Used Firefox and tried on both tampermonkey and violentmonkey. Is it possible for you to save and post the edited version of your ehunter to test for myself?
> 
> Here you go, copied right from my violentmonkey script editor into notepad++. Sorry i cant be of more help. [ehunter.zip](https://github.com/user-attachments/files/17529036/ehunter.zip)

Although this still doesn't work on my Chrome, thank you anyway! I plan to try switching browsers next.

**Comment by AzureZakura** [comment]
> > I also use notepad++, and copied but still get the infinite reading bug. Used Firefox and tried on both tampermonkey and violentmonkey. Is it possible for you to save and post the edited version of your ehunter to test for myself?
> 
> Here you go, copied right from my violentmonkey script editor into notepad++. Sorry i cant be of more help. [ehunter.zip](https://github.com/user-attachments/files/17529036/ehunter.zip)

Tried on Firefox, still get infinite reading bug. Thanks for trying!

**Comment by Secretsquirrel73** [comment]
> > I also use notepad++, and copied but still get the infinite reading bug. Used Firefox and tried on both tampermonkey and violentmonkey. Is it possible for you to save and post the edited version of your ehunter to test for myself?
> 
> Here you go, copied right from my violentmonkey script editor into notepad++. Sorry i cant be of more help. [ehunter.zip](https://github.com/user-attachments/files/17529036/ehunter.zip)

I have the same issue. I really think its how the information is being transferred as we are getting errors when we port the text from notepad to tampermonkey. Might be we are using regular notepad, you are using++, or something else.

Appreciate you trying at least.

**Comment by cshai-wq** [comment]
改完好使了
Thank you

**Comment by SasebonoShigure** [comment]
> > I also use notepad++, and copied but still get the infinite reading bug. Used Firefox and tried on both tampermonkey and violentmonkey. Is it possible for you to save and post the edited version of your ehunter to test for myself?
> 
> Here you go, copied right from my violentmonkey script editor into notepad++. Sorry i cant be of more help. [ehunter.zip](https://github.com/user-attachments/files/17529036/ehunter.zip)

still getting infinite reading problem 😢

**Comment by W0910** [comment]
> https://github.com/xmcp/eHunter/tree/fix-198 is my fixed branch. The thumbnail issue is also fixed in this branch (earlier in the fix-192 branch).
> 
> You can try the code here: [inject.zip](https://github.com/user-attachments/files/17526345/inject.zip)

Sorry，I know little about code. As the comments said, I open my bug eHunter in Violentmonkey, then deleted all contents below 【// ==/UserScript==】and ovewrite by 【inject.js】, but it dosn't work, just loading constantly. Any suggestion?

**Comment by strikingthemoon** [comment]
@xmcp when i use your script, i need to reload to get it to work. something related to read thumb & pageinfos from cache.

to other lads that still can't work it out check your settings. the script only works if your thumbnail size is normal and Gallery Page Thumbnail Labeling is none.

**Comment by AzureZakura** [comment]
> @xmcp ~when i use your script, i need to reload to get it to work. something related to read thumb & pageinfos from cache. ~
> 
> nvm, resetting cache fixed it.
> 
> to other lads that still can't work it out check your settings. the script only works if your thumbnail size is normal and Gallery Page Thumbnail Labeling is none.

Reset cache, made sure thumbnail size and gallery page thumbnail labeling was set to none. Same error.
![image](https://github.com/user-attachments/assets/30b3e5ba-7d7f-47a9-aa78-8115f50935fa)
![image](https://github.com/user-attachments/assets/88e3aedf-85cf-4d32-8aa2-5504158fbd26)

**Comment by AzureZakura** [comment]
> @xmcp ~when i use your script, i need to reload to get it to work. something related to read thumb & pageinfos from cache. ~
> 
> nvm, resetting cache fixed it.
> 
> to other lads that still can't work it out check your settings. the script only works if your thumbnail size is normal and Gallery Page Thumbnail Labeling is none.

Tried it, and it seems to have worked. Thanks!

**Comment by SasebonoShigure** [comment]
> > @xmcp ~when i use your script, i need to reload to get it to work. something related to read thumb & pageinfos from cache. ~
> > nvm, resetting cache fixed it.
> > to other lads that still can't work it out check your settings. the script only works if your thumbnail size is normal and Gallery Page Thumbnail Labeling is none.
> 
> Tried it, and it seems to have worked. Thanks! For anyone else having trouble, try making sure these settings are set like the images below and of course don't forget to click apply at the bottom of your settings. ![image](https://private-user-images.githubusercontent.com/54540733/380432931-e28ce747-4626-4f0d-bdb9-316291723612.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTY0NDEsIm5iZiI6MTcyOTk1NjE0MSwicGF0aCI6Ii81NDU0MDczMy8zODA0MzI5MzEtZTI4Y2U3NDctNDYyNi00ZjBkLWJkYjktMzE2MjkxNzIzNjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE1MjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MjVhY2JiNGFmMDFiZmViMTc1MTkwMGI3Y2IxYjgxMzlkZmNhYzk5MjZjYWRmMzZhYWYwNjhlZTczNmIyMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PDsIjC0TBe44c4TisgKYFzsKT4gW4gYOmB1Q9IAWYHs) ![image](https://private-user-images.githubusercontent.com/54540733/380432988-ebd61df9-e574-4f29-9b03-874e2f16647e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTY0NDEsIm5iZiI6MTcyOTk1NjE0MSwicGF0aCI6Ii81NDU0MDczMy8zODA0MzI5ODgtZWJkNjFkZjktZTU3NC00ZjI5LTliMDMtODc0ZTJmMTY2NDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE1MjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiODRlMzY4NmE1ZTg4OWY1ZDZmMDAyZmMxN2FlZDZjOTJjZDM5ZWI5MDEyNmUyZDBkNDBlMzI1ODYyZjg0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PJkOJyqWanmxAg4VJQM-prutvfI-I7pvAyJ337GgFUw)

it works! If anyone having infinite reading problem and can't have the chance to reset the cache, switch to the original version of eHunter and e-hentai, where you could have it load normally.

**Comment by GhostEx667** [comment]
> > > @xmcp ~when i use your script, i need to reload to get it to work. something related to read thumb & pageinfos from cache. ~
> > > nvm, resetting cache fixed it.
> > > to other lads that still can't work it out check your settings. the script only works if your thumbnail size is normal and Gallery Page Thumbnail Labeling is none.
> > 
> > 
> > Tried it, and it seems to have worked. Thanks! For anyone else having trouble, try making sure these settings are set like the images below and of course don't forget to click apply at the bottom of your settings. ![image](https://private-user-images.githubusercontent.com/54540733/380432931-e28ce747-4626-4f0d-bdb9-316291723612.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTY0NDEsIm5iZiI6MTcyOTk1NjE0MSwicGF0aCI6Ii81NDU0MDczMy8zODA0MzI5MzEtZTI4Y2U3NDctNDYyNi00ZjBkLWJkYjktMzE2MjkxNzIzNjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE1MjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3MjVhY2JiNGFmMDFiZmViMTc1MTkwMGI3Y2IxYjgxMzlkZmNhYzk5MjZjYWRmMzZhYWYwNjhlZTczNmIyMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PDsIjC0TBe44c4TisgKYFzsKT4gW4gYOmB1Q9IAWYHs) ![image](https://private-user-images.githubusercontent.com/54540733/380432988-ebd61df9-e574-4f29-9b03-874e2f16647e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5NTY0NDEsIm5iZiI6MTcyOTk1NjE0MSwicGF0aCI6Ii81NDU0MDczMy8zODA0MzI5ODgtZWJkNjFkZjktZTU3NC00ZjI5LTliMDMtODc0ZTJmMTY2NDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDE1MjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiODRlMzY4NmE1ZTg4OWY1ZDZmMDAyZmMxN2FlZDZjOTJjZDM5ZWI5MDEyNmUyZDBkNDBlMzI1ODYyZjg0NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PJkOJyqWanmxAg4VJQM-prutvfI-I7pvAyJ337GgFUw)
> 
> it works! If anyone having infinite reading problem and can't have the chance to reset the cache, switch to the original version of eHunter and e-hentai, where you could have it load normally.

Apparently, I'm too dumb.....
It still doesn't work for me, everything worked fine yesterday with the code replacement. but stopped working today.
No matter how many times I reset the cache, and change the settings like in the screenshot, on Exh infinite loading.
E-h, works on the original version of the script, but without the thumbnails....

**Comment by mylaluna** [comment]
I don't think the issue is completely fixed. 

For every book, the fix script will begin from an endless loading with the error in console: parsing img html failed. It may be in Large mode.

I need to refresh the page, then the content is correctly displayed with console message:
[CacheService] read imgPageInfos from cache

The fact that I have to refresh page for every book is a bit annoying.

**Comment by SasebonoShigure** [comment]
> Apparently, I'm too dumb..... It still doesn't work for me, everything worked fine yesterday with the code replacement. but stopped working today. No matter how many times I reset the cache, and change the settings like in the screenshot, on Exh infinite loading. E-h, works on the original version of the script, but without the thumbnails....

Well actually, i find it stuck at waiting or reading from time to time now, still very unstable

**Comment by xmcp** [comment]
> I am fixing it, please waiting for update.

Btw do you plan to fix #192 as well?

**Comment by hanFengSan** [comment]
fixed in v2.7.5 :)
https://openuserjs.org/scripts/alexchen/eHunter

**Comment by mbahArip** [comment]
> fixed in v2.7.5 :) https://openuserjs.org/scripts/alexchen/eHunter

Work perfectly on e-h, but still stuck on `Reading...` loading at exh, both on 100x and 200x mode (have tried clear site cache, and local storage)
Need to change `item.children[0]` to `item.querySelector('div[style]')` on [this line](https://github.com/hanFengSan/eHunter/commit/78537617d43e9568a00bdf044c9e588e4de0d55c#diff-fe7edefc7c4586c199ab60099529b4d6efecc3cbafc5dc153d220dd21953fb78R21) to make it work on exh

Is there a reason for using children instead of query selector?

**Comment by SasebonoShigure** [comment]
> fixed in v2.7.5 :) https://openuserjs.org/scripts/alexchen/eHunter

`This IP address has been temporarily banned due to an excessive request rate. This probably means you are using automated mirroring/harvesting software or share the IP address with someone who does. The ban expires in 54 minutes and 14 seconds`
this showed up today after using v2.7.5 for a while encountering some infinite reading problem (yes, it still happens from time to time with 2.7.5). It is actually banning my account although it says it is banning IP. Before being banned, I've noticed Image Limit growing exccesively. I wonder if it is relevant to the infinit reading :(

**Comment by KeeKalm** [comment]
> fixed in v2.7.5 :) https://openuserjs.org/scripts/alexchen/eHunter
This fix is not working in my environment. When browsing `exhentai`, I keep getting prompt `Reading`.

**Comment by KeeKalm** [comment]
> fixed in v2.7.5 :) https://openuserjs.org/scripts/alexchen/eHunter

This fix is not working in my environment. When browsing exhentai, I keep getting prompt Reading.

**Comment by hanFengSan** [comment]
> > fixed in v2.7.5 :) https://openuserjs.org/scripts/alexchen/eHunter
> 
> This fix is not working in my environment. When browsing exhentai, I keep getting prompt Reading.



> > fixed in v2.7.5 :) https://openuserjs.org/scripts/alexchen/eHunter
> 
> Work perfectly on e-h, but still stuck on `Reading...` loading at exh, both on 100x and 200x mode (have tried clear site cache, and local storage) Need to change `item.children[0]` to `item.querySelector('div[style]')` on [this line](https://github.com/hanFengSan/eHunter/commit/78537617d43e9568a00bdf044c9e588e4de0d55c#diff-fe7edefc7c4586c199ab60099529b4d6efecc3cbafc5dc153d220dd21953fb78R21) to make it work on exh
> 
> Is there a reason for using children instead of query selector?

Could you provide me with a test gallery link?

**Comment by hanFengSan** [comment]
> > fixed in v2.7.5 :) https://openuserjs.org/scripts/alexchen/eHunter
> 
> This fix is not working in my environment. When browsing exhentai, I keep getting prompt Reading.

Could you provide me with a test gallery link?

**Comment by mbahArip** [comment]
> Could you provide me with a test gallery link?

You can change the domain from e-hentai to exhentai
After checking the structure, the reason it doesn't work on exhentai gallery is because it have different DOM structure

Here are e-hentai gallery DOM structure
![image](https://github.com/user-attachments/assets/e9802ab3-d1fa-410e-b1a1-b9a9362469db)

This one is exhentai gallery DOM structure
![image](https://github.com/user-attachments/assets/3d9a13e0-c6f7-4f02-8b78-7b0c9aebe6fb)

**Comment by Twilicious** [comment]
> > fixed in v2.7.5 :) https://openuserjs.org/scripts/alexchen/eHunter
> 
> `This IP address has been temporarily banned due to an excessive request rate. This probably means you are using automated mirroring/harvesting software or share the IP address with someone who does. The ban expires in 54 minutes and 14 seconds` this showed up today after using v2.7.5 for a while encountering some infinite reading problem (yes, it still happens from time to time with 2.7.5). It is actually banning my account although it says it is banning IP. Before being banned, I've noticed Image Limit growing exccesively. I wonder if it is relevant to the infinite reading :(

While the new fix does work for me on ex, I think it is loading the full size images instead of the resized ones causing the image limit to be reached much faster. Switching back to the fix version posted here yesterday the limit goes up much slower.

**Comment by awdrrawd** [comment]
I currently use the simplest way to make an emergency, others can refer to it.
I don't know Script, so I wrote it using GPT.

我目前用的是最簡單的方法來應急，其他人可以參考一下。
我不懂語法，所以這是用GPT寫的。

https://openuserjs.org/install/awdrrawd/ExHentai_Image_Redirect_to_E-Hentai.user.js

**Comment by hanFengSan** [comment]
> > Could you provide me with a test gallery link?
> 
> You can change the domain from e-hentai to exhentai After checking the structure, the reason it doesn't work on exhentai gallery is because it have different DOM structure
> 
> Here are e-hentai gallery DOM structure ![image](https://private-user-images.githubusercontent.com/62494292/380521204-e9802ab3-d1fa-410e-b1a1-b9a9362469db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODI5MDIsIm5iZiI6MTczMDA4MjYwMiwicGF0aCI6Ii82MjQ5NDI5Mi8zODA1MjEyMDQtZTk4MDJhYjMtZDFmYS00MTBlLWIxYTEtYjlhOTM2MjQ2OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MTA1NGIxNzUyZWJhNzdlZTg1NTc1ZjczYTg2MzBkZjM0MDc5NDVmOTI2NWIwMzQ4Y2YyMjU2ZDg5YTllYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oS5HLiMWg11IWQ1BuvM6IAWgL3kohc84H4N9iJu-tlg)
> 
> This one is exhentai gallery DOM structure ![image](https://private-user-images.githubusercontent.com/62494292/380521236-3d9a13e0-c6f7-4f02-8b78-7b0c9aebe6fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODI5MDIsIm5iZiI6MTczMDA4MjYwMiwicGF0aCI6Ii82MjQ5NDI5Mi8zODA1MjEyMzYtM2Q5YTEzZTAtYzZmNy00ZjAyLThiNzgtN2IwYzlhZWJlNmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZDRlYTdmYWRjZjcwZDE4MDI3NDE4YzZjMzdjOTQzMTVlYTFiYWE2MmFjNTg1NGZhZjU4MjJmZTQ1M2UzZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sh1fA_-tigNbJ-bxKEP4GQ2h3_L8BrIUWolSwSVBevQ)

It is weird, bacause it's work fine for me.
![image](https://github.com/user-attachments/assets/f38d311a-e6b0-4c0b-b24a-1c87797324a2)

**Comment by hanFengSan** [comment]
> > Could you provide me with a test gallery link?
> 
> You can change the domain from e-hentai to exhentai After checking the structure, the reason it doesn't work on exhentai gallery is because it have different DOM structure
> 
> Here are e-hentai gallery DOM structure ![image](https://private-user-images.githubusercontent.com/62494292/380521204-e9802ab3-d1fa-410e-b1a1-b9a9362469db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODI5MDIsIm5iZiI6MTczMDA4MjYwMiwicGF0aCI6Ii82MjQ5NDI5Mi8zODA1MjEyMDQtZTk4MDJhYjMtZDFmYS00MTBlLWIxYTEtYjlhOTM2MjQ2OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2MTA1NGIxNzUyZWJhNzdlZTg1NTc1ZjczYTg2MzBkZjM0MDc5NDVmOTI2NWIwMzQ4Y2YyMjU2ZDg5YTllYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oS5HLiMWg11IWQ1BuvM6IAWgL3kohc84H4N9iJu-tlg)
> 
> This one is exhentai gallery DOM structure ![image](https://private-user-images.githubusercontent.com/62494292/380521236-3d9a13e0-c6f7-4f02-8b78-7b0c9aebe6fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwODI5MDIsIm5iZiI6MTczMDA4MjYwMiwicGF0aCI6Ii82MjQ5NDI5Mi8zODA1MjEyMzYtM2Q5YTEzZTAtYzZmNy00ZjAyLThiNzgtN2IwYzlhZWJlNmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDAyMzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwZDRlYTdmYWRjZjcwZDE4MDI3NDE4YzZjMzdjOTQzMTVlYTFiYWE2MmFjNTg1NGZhZjU4MjJmZTQ1M2UzZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Sh1fA_-tigNbJ-bxKEP4GQ2h3_L8BrIUWolSwSVBevQ)

Oh, I see the difference, 'infinite-scroll-page'. It may be the reason. Where can I enable this mode? I've forgotten where to set it up.

**Comment by mbahArip** [comment]
> Oh, I see the difference, 'infinite-scroll-page'. It may be the reason. Where can I enable this mode? I've forgotten where to set it up.

`infinite-scroll-page` is actually from another script. even without it, the gallery still stuck on `Reading...`
e-hentai DOM is `div#gdt > div.gdtm > div > a > img`, meanwhile exhentai DOM is `div#gdt > a > div > div`

this causing the `match`  to get the width and height to be null
since on exhentai `t.children[0]` will point to the `a` element
![image](https://github.com/user-attachments/assets/2486f99d-a74d-487d-a15e-971e645302a9)
![image](https://github.com/user-attachments/assets/f4472656-2321-457a-9f68-5b7f8a65e6f7)

**Comment by hanFengSan** [comment]
> > Oh, I see the difference, 'infinite-scroll-page'. It may be the reason. Where can I enable this mode? I've forgotten where to set it up.
> 
> `infinite-scroll-page` is actually from another script. even without it, the gallery still stuck on `Reading...` e-hentai DOM is `div#gdt > div.gdtm > div > a > img`, meanwhile exhentai DOM is `div#gdt > a > div > div`
> 
> this causing the `match` to get the width and height to be null since on exhentai `t.children[0]` will point to the `a` element ![image](https://private-user-images.githubusercontent.com/62494292/380590256-2486f99d-a74d-487d-a15e-971e645302a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjc1NTUsIm5iZiI6MTczMDEyNzI1NSwicGF0aCI6Ii82MjQ5NDI5Mi8zODA1OTAyNTYtMjQ4NmY5OWQtYTc0ZC00ODdkLWExNWUtOTcxZTY0NTMwMmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE0NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwM2E3YmMzYWU0MWRkN2I3NTA1YTIxMTc2MWM5ZTM5M2Y5MDkxZDNlN2JhYTcyMDYyZmMzZGE1Njc2NDU4NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NSWPpleouJAjSy0TZz-_jg9pOvDiQLSmTBwaR-LTj2g) ![image](https://private-user-images.githubusercontent.com/62494292/380590826-f4472656-2321-457a-9f68-5b7f8a65e6f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjc1NTUsIm5iZiI6MTczMDEyNzI1NSwicGF0aCI6Ii82MjQ5NDI5Mi8zODA1OTA4MjYtZjQ0NzI2NTYtMjMyMS00NTdhLTlmNjgtNWI3ZjhhNjVlNmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE0NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNmM4M2VjMmRiOWI5YTI0NTU1NzRhZTNkMWMwZTgzM2M1Yzc3OTczYTdjYTQ4YWRiOTI0YzhhZmVkNzgzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UjNo1Zr2CQiqfSCb7FUbP4-CN6bhb7Kk--tF9TeT418)



> > Oh, I see the difference, 'infinite-scroll-page'. It may be the reason. Where can I enable this mode? I've forgotten where to set it up.
> 
> `infinite-scroll-page` is actually from another script. even without it, the gallery still stuck on `Reading...` e-hentai DOM is `div#gdt > div.gdtm > div > a > img`, meanwhile exhentai DOM is `div#gdt > a > div > div`
> 
> this causing the `match` to get the width and height to be null since on exhentai `t.children[0]` will point to the `a` element ![image](https://private-user-images.githubusercontent.com/62494292/380590256-2486f99d-a74d-487d-a15e-971e645302a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjc1NTUsIm5iZiI6MTczMDEyNzI1NSwicGF0aCI6Ii82MjQ5NDI5Mi8zODA1OTAyNTYtMjQ4NmY5OWQtYTc0ZC00ODdkLWExNWUtOTcxZTY0NTMwMmE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE0NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwM2E3YmMzYWU0MWRkN2I3NTA1YTIxMTc2MWM5ZTM5M2Y5MDkxZDNlN2JhYTcyMDYyZmMzZGE1Njc2NDU4NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NSWPpleouJAjSy0TZz-_jg9pOvDiQLSmTBwaR-LTj2g) ![image](https://private-user-images.githubusercontent.com/62494292/380590826-f4472656-2321-457a-9f68-5b7f8a65e6f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjc1NTUsIm5iZiI6MTczMDEyNzI1NSwicGF0aCI6Ii82MjQ5NDI5Mi8zODA1OTA4MjYtZjQ0NzI2NTYtMjMyMS00NTdhLTlmNjgtNWI3ZjhhNjVlNmY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDE0NTQxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkNmM4M2VjMmRiOWI5YTI0NTU1NzRhZTNkMWMwZTgzM2M1Yzc3OTczYTdjYTQ4YWRiOTI0YzhhZmVkNzgzMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UjNo1Zr2CQiqfSCb7FUbP4-CN6bhb7Kk--tF9TeT418)

I understand what you're saying, but I'm unable to reproduce the issue on my end. I'm curious to know why the DOM appears differently for you and me. Could you possibly give me a link to the gallery where you're encountering the problem? It might help determine if the issue is related to a specific gallery. Additionally, if possible, please provide a screenshot of the thumbnail section on the gallery's main page. Being able to reproduce  the case or understand the cause would enable me to apply an accurate fix.

**Comment by hanFengSan** [comment]
It might be related to different settings. Could you please send me a screenshot of your settings page?
https://exhentai.org/uconfig.php

**Comment by hanFengSan** [comment]
> @xmcp ~when i use your script, i need to reload to get it to work. something related to read thumb & pageinfos from cache.~
> 
> nvm, resetting cache fixed it.
> 
> to other lads that still can't work it out check your settings. the script only works if your thumbnail size is normal and Gallery Page Thumbnail Labeling is none.

Oh, this is likely related to permissions. These are the options available to me.......
![image](https://github.com/user-attachments/assets/3d48ba18-bd0f-40c4-a63d-38f50f08f528)

**Comment by mbahArip** [comment]
> > 
> > 
> > I understand what you're saying, but I'm unable to reproduce the issue on my end. I'm curious to know why the DOM appears differently for you and me. Could you possibly give me a link to the gallery where you're encountering the problem? It might help determine if the issue is related to a specific gallery. Additionally, if possible, please provide a screenshot of the thumbnail section on the gallery's main page. Being able to reproduce the case or understand the cause would enable me to apply an accurate fix.
> 
> My DOM looks like this: https://exhentai.org/g/2195608/45a42744bf/ ![image](https://private-user-images.githubusercontent.com/16065654/380771345-715a3c92-5447-415a-843d-97c4e7fb3800.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTc2OTksIm5iZiI6MTczMDE1NzM5OSwicGF0aCI6Ii8xNjA2NTY1NC8zODA3NzEzNDUtNzE1YTNjOTItNTQ0Ny00MTVhLTg0M2QtOTdjNGU3ZmIzODAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIzMTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YjZlYzg5ZTYyNGYwZDYzYjRhYmI1YTUxYzMyMzRmYzE0ZGY3YjhjMGMxODVkM2M0MDJlOGE1Nzg1MTM3YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4Egaw7tTItOTN4G_WCv2NhVlrCrt2DaVjSTEy2KtwFU) ![image](https://private-user-images.githubusercontent.com/16065654/380772396-e5a66ab2-6ada-40d2-9fce-8413a63aa366.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNTc2OTksIm5iZiI6MTczMDE1NzM5OSwicGF0aCI6Ii8xNjA2NTY1NC8zODA3NzIzOTYtZTVhNjZhYjItNmFkYS00MGQyLTlmY2UtODQxM2E2M2FhMzY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDIzMTYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MzU1MDY4NTE2ZWIyYTEwOWE2MjViMTlhNzY0ZWExZWNjNDMyZmMyNjBiYWYyZTk3ZTA2OWM1ZThmZjNhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._mqrU6LaEzJitwO2IIZPa-87t5sPM2JvcsPoZpnLP2g)

I'm sorry of the infinite-scroll causing confusion, if I disable it, the DOM looks exactly like yours.
here my settings:
![image](https://github.com/user-attachments/assets/45d36da6-f86b-4856-be87-ce2a7ee9ec7b)
![image](https://github.com/user-attachments/assets/c3a58921-39bd-4670-b415-9a87f8e3cb19)
![image](https://github.com/user-attachments/assets/1ae22726-0a27-4956-9643-ca3423550214)

**Comment by hanFengSan** [comment]
v2.7.6 has released:
https://openuserjs.org/scripts/alexchen/eHunter

**Comment by SasebonoShigure** [comment]
> v2.7.6 has released:
> https://openuserjs.org/scripts/alexchen/eHunter

It seems that if you are viewing several galleries at the same time, i.e. in different tabs, all of them will still get stuck either in READING or WAITING for a good while, about tens of seconds.

**Comment by strikingthemoon** [comment]
@hanFengSan recently I got the gallery be capped at 20/40 images. Also it always changes my thumbnail setting to auto. I think the script needs an update.

**Comment by hanFengSan** [comment]
Yes, I will fix it later.

strikingthemoon ***@***.***> 于 2024年11月5日周二 16:36写道：

**Comment by loserwa** [comment]
周日回复或未必回复
